### ISSUE TITLE
Add Check Availability page

### ISSUE THREAD

**Issue by preetjdp** [IndiaVaccineIN/india-vaccine-frontend#2]
Add a page for checking the availability of the vaccine

**Figma**

https://www.figma.com/file/ifevQqQqavhzo6U56oV6Zg/India-Vaccine?node-id=69%3A5

** Bugs Mentioned on Notion **
https://www.notion.so/f8231a5a319c404aaa2ce503f0c0000c?v=df63a6568eff4e5bb2c9c4efc7667e8d

**TODO**

- [x] Create baseline page
- [x] Create baseline layout of the page
- [x] Utilize the APIs
- [ ] Ship the page (done for dev version)
- [ ] Fix the bugs
- [ ] Add in the error states (eg: no results from cowin api shouldn't show up blank)

**References**

- https://next-auth.js.org
- https://devrecipes.net/modal-component-with-next-js/
- https://www.npmjs.com/package/react-modal

**Comment by preetjdp** [comment]
Marking this as done as the baseline PR was merged
